name: Build Payment Services Docker Image

on:
  push:
    paths:
      - 'Cafe_Management_System/payment-services/**'
  pull_request:
    paths:
      - 'Cafe_Management_System/payment-services/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/payment-services:latest Cafe_Management_System/payment-services
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/payment-services:latest
